services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HISTFILE: /app/tmp/.bash_history
    volumes:
      - ./:/app
      - go-build:/root/.cache/go-build
      - go-modules:/go/pkg/mod
    ports:
      - 3000:3000

  air: &air
    image: cosmtrek/air
    command: "air init"
    working_dir: /app
    volumes:
      # - nfsmount:/app
      - ./:/app
      - go-build:/root/.cache/go-build
      - go-modules:/go/pkg/mod
    ports:
      - 3000:3000

volumes:
  go-build:
  go-modules:
#   nfsmount:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#       device: :${PWD}
